export const fb_link = 'https://www.facebook.com/adam.kulig.7';
export const github_link ='https://github.com/adamkulig';
export const linkedin_link ='https://www.linkedin.com/in/adam-kulig-7a8353164/';
export const piggame_link_live = 'https://adamkulig.github.io/pig-game-react/';
export const piggame_link_code = 'https://github.com/adamkulig/pig-game-react';
export const todo_link_live = 'https://adamkulig.github.io/todo-react/';
export const todo_link_code = 'https://github.com/adamkulig/todo-react';
export const recipes_link_live = '#';
export const recipes_link_code = 'https://github.com/adamkulig/recipes-search-engine-react-redux';
